### ISSUE TITLE
no train.csv file in datasets

### ISSUE THREAD

**Issue by Gerry-j** [JinyanSu1/AGGD#1]
Hello, I downloaded the NQ dataset automatically when I executed main.py, but when I unzipped it, there was no train.csv file in datasets.

**Comment by JinyanSu1** [comment]
Did you pass dataset =`nq-train` and pass split =`train` ?

**Comment by Gerry-j** [comment]
> Did you pass dataset =`nq-train` and pass split =`train` ?

![屏幕截图 2024-08-15 112404](https://github.com/user-attachments/assets/61f8bdc2-dc57-4109-89fe-aa6378edffec)

When I execute load_data there is no nq-train in the downloaded nq folder. Do you mean that I need to download additional nq-train?

**Comment by Gerry-j** [comment]
> Did you pass dataset =`nq-train` and pass split =`train` ?

Thank you for your reply，I find that I need to download nq-train.zip in https://public.ukp.informatik.tu-darmstadt.de/thakur/BEIR/datasets/
